plugins:
  - jekyll-default-layout

#theme: jekyll-theme-Modernist
title: YOUR TITLE
description: YOUR DESCRIPTION
remote_theme: just-the-docs/just-the-docs@v0.5.2
url: https:///KorelU.githb.io/Practacing-GitHub-Pages
